#!/bin/bash
apm install atom-beautify
apm install atom-ternjs
apm install atom-typescript
apm install autocomplete-paths
apm install color-picker
apm install editorconfig
apm install emmet
apm install file-icons
apm install git-control
apm install git-log
apm install git-plus
apm install git-status
apm install highlight-line
apm install highlight-selected
apm install language-fish-shell
apm install language-mongodb
apm install language-rust
apm install language-scala
apm install linter
apm install linter-eslint
apm install linter-rust
apm install merge-conflicts
apm install minimap
apm install minimap-cursorline
apm install minimap-find-and-replace
apm install minimap-highlight-selected
apm install minimap-pigments
apm install pigments
apm install racer
apm install script
apm install todo-show
